(function() {
  var Schema, mongoose, usuarioRedmineSchema;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  usuarioRedmineSchema = new Schema({
    redmineID: Number,
    nome: String,
    ativo: Boolean
  });

  module.exports = mongoose.model('UsuarioRedmine', usuarioRedmineSchema);

  // ---
// generated by js2coffee 2.2.0

}).call(this);
